#!/usr/bin/sh
set -a
PROJECT="fzf-apps"
blacklisted_words="$(pass show sensitive/axgkl)" # list of '::' seperated words to fail when occurring in committed files
conda_project_tools="tmux"
pyver="3.7"                                                                              # min version
versioning=calver                                                                        # for git changelog
set +a

git config user.email "g_kl_es_sing_er@gmx.de"
source ./make -a # giving us make docs, make tests, .. -a activates venv
echo "sourced ./make"
